# Generated by Django 5.0.6 on 2026-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                ("total_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "published_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("language", models.CharField(default="en", max_length=10)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx")
                ],
            },
        ),
    ]
